name: Deploy to Coolify
on:
    push:
        branches: [ "main" ]

jobs:
    amd64:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v3
            -   name: Deploy to Coolify
                run: |
                    curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
